### ISSUE TITLE
Wrong detection of JAVA library as Android lib

### ISSUE THREAD

**Issue by Hollerweger** [Mobbeel/fataar-gradle-plugin#21]
What are the steps to reproduce this issue?
-------------------------------------------
Add java library api dependency

What happens?
-------------
Library is detected as Android library and missing android property

Version:
Tested with 2.0.1, 2.0.2 & 2.0.2
Gradle: 4.8
Android Gradle Plugin: 3.2.1

Logs: 
```
> Task :fat-aar:assembleRelease

> Task :fat-aar:copyReleaseDependencies FAILED
int string app_name 0x7f150001
Internal android dependency detected -> java-lib
* What went wrong:
Execution failed for task ':fat-aar:copyReleaseDependencies'.
> Could not get unknown property 'android' for project ':java-lib' of type org.gradle.api.Project.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':fat-aar:copyReleaseDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:11
0)
....
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'android' for project ':java-lib' of type org
.gradle.api.Project.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)

```

**Comment by oscarcpozas** [comment]
fat-aar plugin doesn't support 3.2.x Gradle plugin yet, I'm working on it.
You can see the advances in this issue (https://github.com/Mobbeel/fataar-gradle-plugin/issues/28)
